name: Playwright and Commit Screenshot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-playwright-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # 기본 GITHUB_TOKEN 권한 유지
        fetch-depth: 0            # 전체 커밋 히스토리 가져오기

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install

    - name: Run Playwright script
      run: python script.py

    - name: Configure git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add and commit screenshot
      run: |
        git add naver.png
        git commit -m "Add naver.png screenshot from GitHub Actions" || echo "No changes to commit"

    - name: Push changes
      run: git push
