name: Run Playwright Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install

    - name: Run Playwright script
      run: |
        python script.py

    - name: Upload screenshot
      uses: actions/upload-artifact@v3
      with:
        name: naver-screenshot
        path: naver.png
