name: Playwright Test with Screenshot Commit

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # 👈 Push 권한 부여!

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install playwright
        playwright install

    - name: Run Playwright script
      run: python script.py

    - name: Commit screenshot
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add smart_farm.png
        git commit -m "Add screenshot (smart_farm.png)" || echo "No changes to commit"
        git push
